name: "bash"
version: "5.3"
release: 1
description: "GNU Bourne Again Shell"

dependencies:
  - "ncurses"
  - "readline"

makedependencies:
  - "gcc"
  - "make"
  - "pkg-config"

sources:
  - url: "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"
    checksum: "0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"

build:
  script: |
    ./configure --prefix=/usr --with-curses
    make -j${JOBS}

install:
  script: |
    make DESTDIR=${DESTDIR} install

